stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

VBET-FR-test-cases:
  image: cypress/browsers
  stage: test
  script:
    - npm ci
    - npm install mochawesome # Ensure mochawesome is installed (check your package.json)
    - npx cypress run --headless --browser chrome --config viewportWidth=1366,viewportHeight=768
    - echo "Cypress tests complete"
  artifacts:
    when: always
    paths:
      - cypress/reports/mocha/*.html
      - cypress/reports/mocha/*.json
      - mochawesome-report/**  # Correct folder name for mochawesome report
      - cypress/screenshots/**/*.png
    expire_in: 7 days
  after_script:
    - echo "Test run complete"

VBET-LAT-test-cases:
  stage: test
  script:
    - echo "Linting code... This will take about 10 seconds."
    - sleep 10
    - echo "No lint issues found."

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
