stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

VBET-FR-test-cases:
  image: cypress/browsers
  stage: test
  script:
    - npm ci
    - npm install mocha-awesome  # Correct package name here
    - npx cypress run --headless --reporter mochawesome
  artifacts:
    when: always
    paths:
      - mochaawesome-report/**
      - cypress/screenshots/**/*.png
      - cypress/videos/**/*.mp4
    expire_in: 7 days


lint-test-job:
  stage: test
  script:
    - echo "Linting code... This will take about 10 seconds."
    - sleep 10
    - echo "No lint issues found."

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
