stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

VBET-FR-test-cases:
  image: cypress/browsers
  stage: test
  before_script:
    - apt-get update -y
    - ip a
    - apt-get install -y xvfb # Install Xvfb for virtual display
    - apt-get install -y google-chrome-stable # Install Google Chrome if not already installed
    - export DISPLAY=:99 # Set the display for Xvfb
    - Xvfb :99 -screen 0 1366x768x24 & # Start Xvfb with a virtual display
  script:
    - npm ci
    - npm install mochawesome # Ensure mochawesome is installed (check your package.json)
    - npx cypress run --browser chrome --headed # Run Cypress in headed mode (with GUI)
    - echo "Cypress tests complete"
  artifacts:
    when: always
    paths:
      - cypress/reports/mocha/*.html
      - cypress/reports/mocha/*.json
      - mochawesome-report/**  # Correct folder name for mochawesome report
      - cypress/screenshots/**/*.png
    expire_in: 7 days
  after_script:
    - echo "Test run complete"

VBET-LAT-test-cases:
  stage: test
  script:
    - echo "Linting code... This will take about 10 seconds."
    - sleep 10
    - echo "No lint issues found."

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
